import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Home_main from './Home_main'


export default function Home() {
  return (
    <div className={styles.container}> 
      <Head>
        <title>Khushi metal and alloys wer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"  />
      </Head>

      <Home_main/>

    </div>
  )
}
